# Generated by Django 4.2 on 2023-04-23 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitTrackerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'verbose_name_plural': 'Habits'},
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 13, 55, 46, 625527, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='target',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 23, 13, 55, 46, 625527, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='target',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 23, 13, 55, 46, 625527, tzinfo=datetime.timezone.utc)),
        ),
    ]
