# Generated by Django 4.2 on 2023-04-23 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitTrackerApp', '0002_alter_habit_options_alter_habitlog_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitlog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 13, 56, 14, 289634, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='target',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 13, 56, 14, 289128, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='target',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 13, 56, 14, 289128, tzinfo=datetime.timezone.utc)),
        ),
    ]
