# Generated by Django 4.2 on 2023-04-23 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habitTrackerApp', '0003_alter_habitlog_date_alter_target_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitlog',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='target',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='target',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
